### ISSUE TITLE
customizable prefix?

### ISSUE THREAD

**Issue by moet78** [nzlosh/err-stackstorm#24]
What to do to setup customizable prefix? for both the !st2 and !st2help part. 
I am hoping to customize this so we can use the same bot for different environment

**Comment by nzlosh** [comment]
This is a feature I had wanted to include but the problem is more complex than it would appear.

Due to the way triggers are defined (Python function decorators) and the moment user configuration is available to the err-stackstorm plugin, I've not been able to find a way to allow users to customise the trigger without modifying the source code.

That said, I'll take another look at the issue to see if I can find a workaround/solution.

**Comment by nicholasamorim** [comment]
Yeah, same use case here. We can't unify our ST2 deployment because the dev and prod environment do not talk to each other. So we'd like another bot in the channels but can't do because of this.

**Comment by moet78** [comment]
Right now I add a different bot for prod, and also a different channel for prod chatops to get around this. I find it actually is a clean solution as it leave very little room for confusion.  Might also work for you

**Comment by nzlosh** [comment]
@moejarv @nicholasamorim I've created a branch called `plugin_prefix`.  The `st2help` is currently unchangable, but once I find the way to customise it, I'll merge the branch to master.  In the mean time you can test the new feature if you wish.  You just need to add a new variable to the `STACKSTORM` dictionary in `config.py`.  The variable must be placed at the root of the dictionary and is called `plugin_prefix`.

**Comment by nzlosh** [comment]
`plugin_prefix` branch has been updated to allow modification of `st2help` prefix too.
